version: '3.8'
services:
  main-service:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network

  python-service:
    build:
      context: ../python_service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
